# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-31 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.TextField(unique=True)),
                ('pre_work', models.TextField()),
                ('real_work', models.TextField()),
                ('key_result', models.TextField()),
                ('complete_rate', models.TextField(max_length=5)),
                ('tomorrow_work', models.TextField()),
                ('create_ip', models.GenericIPAddressField()),
                ('update_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('username', models.TextField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('ip', models.GenericIPAddressField()),
                ('role', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily.User'),
        ),
    ]
