# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-02 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='name',
            field=models.TextField(),
        ),
    ]
