# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-03 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_auto_20160902_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='user_id',
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='daily.User', verbose_name='\u7528\u6236\u4fe1\u606f\u8868\u4e2d\u5c0d\u61c9\u7684\u4eba'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='complete_rate',
            field=models.TextField(max_length=5, verbose_name='\u5b8c\u6210\u5ea6'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='create_ip',
            field=models.GenericIPAddressField(verbose_name='\u586b\u5bebIP'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(verbose_name='\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='key_result',
            field=models.TextField(verbose_name='\u5173\u952e\u7d50\u679c'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='name',
            field=models.TextField(verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='pre_work',
            field=models.TextField(verbose_name='\u4eca\u65e5\u5de5\u4f5c\u6628\u65e5\u9884\u62a5'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='real_work',
            field=models.TextField(verbose_name='\u4eca\u65e5\u5be6\u969b\u5de5\u4f5c\u5b89\u6392'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='tomorrow_work',
            field=models.TextField(verbose_name='\u660e\u65e5\u5de5\u4f5c\u9884\u62a5'),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='update_datetime',
            field=models.DateTimeField(verbose_name='\u66f4\u65b0\u6642\u9593'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ip',
            field=models.GenericIPAddressField(verbose_name='IP\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='order',
            field=models.IntegerField(verbose_name='\u6392\u5e8f\u6b0a\u503c'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='\u5bc6\u78bc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(verbose_name='\u6b0a\u9650'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(max_length=10, unique=True, verbose_name='\u5de5\u865f'),
        ),
    ]
