# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-03 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_auto_20160903_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.TextField(default='\u6a5f\u69cb\u4e09\u7d44', verbose_name='\u7d44\u5225'),
            preserve_default=False,
        ),
    ]
