# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-03 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_user_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='FtpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField(verbose_name='FTP\u5730\u5740')),
                ('username', models.TextField(max_length=10, verbose_name='\u767b\u9304\u7528\u6236\u540d')),
                ('password', models.TextField(max_length=26, verbose_name='\u767b\u9304\u5bc6\u78bc')),
                ('team', models.TextField(verbose_name='\u7d44\u5225')),
                ('folder1', models.TextField(verbose_name='\u4e0a\u50b3\u6587\u4ef6\u593e1-\u7d44\u5167\u6587\u4ef6\u593e')),
                ('folder2', models.TextField(verbose_name='\u4e0a\u50b3\u6587\u4ef6\u593e2-\u516c\u5171\u6587\u4ef6\u593e')),
            ],
        ),
    ]
