# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0006_user_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='\u5de5\u865f\uff08\u6388\u6b0a->\u7528\u6236\u4e2d\u7684\u7528\u6236\u540d\uff09'),
        ),
    ]
