# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0007_auto_20160905_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(help_text='\u7d44\u9577\u70ba1\uff0c\u7d44\u54e1\u70ba0', verbose_name='\u89d2\u8272'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.OneToOneField(help_text='\u5ec9\u50f9\u5230\u6388\u6b0a->\u7528\u6236\u4e2d\u7684\u7528\u6236\u540d\uff0c\u6240\u4ee5\uff0c\u6dfb\u52a0\u7528\u6236\u524d\u9700\u8981\u5148\u5230\u6388\u6b0a->\u7528\u6236\u4e2d\u6dfb\u52a0\u4e00\u500b\u53ef\u767b\u9678\u7528\u6236', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='\u5de5\u865f'),
        ),
    ]
