# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0010_auto_20160908_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftpinfo',
            name='folder3',
            field=models.TextField(default=1, verbose_name='\u9031\u5831\u4e0a\u50b3\u6587\u4ef6\u593e1-\u7d44\u5167\u6587\u4ef6\u593e'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ftpinfo',
            name='folder4',
            field=models.TextField(default=1, verbose_name='\u9031\u5831\u4e0a\u50b3\u6587\u4ef6\u593e2-\u516c\u5171\u6587\u4ef6\u593e'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ftpinfo',
            name='folder1',
            field=models.TextField(verbose_name='\u65e5\u5831\u4e0a\u50b3\u6587\u4ef6\u593e1-\u7d44\u5167\u6587\u4ef6\u593e'),
        ),
        migrations.AlterField(
            model_name='ftpinfo',
            name='folder2',
            field=models.TextField(verbose_name='\u65e5\u5831\u4e0a\u50b3\u6587\u4ef6\u593e2-\u516c\u5171\u6587\u4ef6\u593e'),
        ),
    ]
