# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0011_auto_20160912_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyreport',
            options={'verbose_name': '\u65e5\u5831\u6578\u64da\u8868', 'verbose_name_plural': '\u65e5\u5831\u6578\u64da\u8868'},
        ),
        migrations.AlterModelOptions(
            name='ftpinfo',
            options={'verbose_name': 'FTP\u516c\u5171\u6587\u4ef6\u593e\u767b\u9304\u4fe1\u606f(\u7528\u65bc"\u5c0e\u51fa\u5e76\u4e0a\u50b3\u81f3\u516c\u5171\u6587\u4ef6\u593e\u529f\u80fd")', 'verbose_name_plural': 'FTP\u516c\u5171\u6587\u4ef6\u593e\u767b\u9304\u4fe1\u606f(\u7528\u65bc"\u5c0e\u51fa\u5e76\u4e0a\u50b3\u81f3\u516c\u5171\u6587\u4ef6\u593e\u529f\u80fd")'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'get_latest_by': 'date', 'verbose_name': '\u7528\u6236\u4fe1\u606f\u8868', 'verbose_name_plural': '\u7528\u6236\u4fe1\u606f\u8868'},
        ),
        migrations.AlterField(
            model_name='ftpinfo',
            name='team',
            field=models.TextField(unique=True, verbose_name='\u7d44\u5225'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyreport',
            unique_together=set([('date', 'name')]),
        ),
    ]
