# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-08 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('daily', '0010_auto_20160908_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='\u5e74\u4efd')),
                ('week', models.IntegerField(verbose_name='\u5468\u6570')),
                ('name', models.TextField(verbose_name='\u59d3\u540d')),
                ('work_plan', models.TextField(verbose_name='\u672c\u5468\u5de5\u4f5c\u8ba1\u5212')),
                ('work_summary', models.TextField(verbose_name='\u672c\u5468\u5de5\u4f5c\u603b\u7ed3')),
                ('next_work', models.TextField(verbose_name='\u4e0b\u5468\u5de5\u4f5c\u8ba1\u5212')),
                ('create_ip', models.GenericIPAddressField(verbose_name='\u586b\u5bebIP')),
                ('update_datetime', models.DateTimeField(verbose_name='\u66f4\u65b0\u6642\u9593')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daily.User', verbose_name='\u7528\u6236\u4fe1\u606f\u8868\u4e2d\u5c0d\u61c9\u7684\u4eba')),
            ],
        ),
    ]
